import json
from datetime import datetime

# Load cookies from JSON (replace with your JSON filename)
with open("cookies.json", "r") as file:
    cookies = json.load(file)

# Open a file to write the Netscape cookie format
with open("cookies_netscape.txt", "w") as file:
    # Write header
    file.write("# Netscape HTTP Cookie File\n")
    file.write("# This file was generated by a script. Edit at your own risk.\n\n")
    
    # Convert each cookie to Netscape format
    for cookie in cookies:
        domain = cookie.get("domain", "")
        flag = "TRUE" if not cookie.get("hostOnly", False) else "FALSE"
        path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        expiration = int(cookie.get("expirationDate", datetime.now().timestamp()))  # Default to current time if missing
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        
        # Write the cookie line
        file.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

print("Cookies converted to Netscape format and saved as 'cookies_netscape.txt'")
