import json

def convert_to_netscape(json_file, netscape_file):
    with open(json_file, "r") as infile:
        cookies = json.load(infile)

    with open(netscape_file, "w") as outfile:
        # Write header for Netscape cookies file
        outfile.write("# Netscape HTTP Cookie File\n")
        outfile.write("# This file is generated by convert_cookies.py\n")
        for cookie in cookies:
            domain = cookie.get("domain", "")
            flag = "TRUE" if cookie.get("hostOnly", False) else "FALSE"
            path = cookie.get("path", "/")
            secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            expiration = str(int(cookie.get("expirationDate", 0))) if "expirationDate" in cookie else "0"
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            # Write each cookie in Netscape format
            outfile.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

if __name__ == "__main__":
    input_file = "hotstar_cookies.json"
    output_file = "hotstar_cookies_netscape.txt"
    convert_to_netscape(input_file, output_file)
    print(f"Converted cookies saved to {output_file}")
